### ISSUE TITLE
What is the license for this skeleton?

### ISSUE THREAD

**Issue by tnishinaga** [SupImDos/embassy-rp-skeleton#4]
Thank you for creating such a great skeleton!

I would like to use this skeleton for my project, but I could not find a license for this skeleton, so I cannot use it.

So, could you please add the license file?

**Comment by SupImDos** [comment]
@tnishinaga Sorry, I never saw this! Probably a bit late now, but I've added the least restrictive license I could find to the repo here: 691af52bc79a94e0c5b91f2d15f5b5f206c8249d. To anyone reading this in the future, feel free to use this skeleton for whatever you want.
